
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    username: spring
    password: spring
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
