version: "3"

services:
  mariadb:
    image: "mariadb:10.5"
    container_name: mariadb-liquibase
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: demo
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - "3306:3306"
